# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, Optional

from .._models import BaseModel

__all__ = ["AgentRunResponse"]


class AgentRunResponse(BaseModel):
    id: Optional[str] = None
    """The unique identifier for the agent completion."""

    description: Optional[str] = None
    """A description of the agent or completion."""

    name: Optional[str] = None
    """The name of the agent."""

    outputs: Optional[object] = None
    """The outputs generated by the agent."""

    success: Optional[bool] = None
    """Indicates whether the agent completion was successful."""

    temperature: Optional[float] = None
    """The temperature setting used for the agent's response generation."""

    timestamp: Optional[str] = None
    """The timestamp when the agent completion was created."""

    usage: Optional[Dict[str, object]] = None
    """Usage statistics or metadata for the agent completion."""
